### ISSUE TITLE
listData.search is not showing expected behaviour

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#112]
In
https://github.com/AssetMantle/modules/blob/d67d671674ebe23bb612c519490ed164e7bf3283/schema/data/base/listData.go#L29
For Test sample:
https://github.com/AssetMantle/modules/blob/d67d671674ebe23bb612c519490ed164e7bf3283/schema/data/base/listData_test.go#L283
It shouldn't give 0 as the data is not available in listData
or for other test sample it should return no of occurrences then it's true but for other data it's wrong

**Comment by deepanshutr** [comment]
returns insertion height no number of occurances
