### ISSUE TITLE
invalid Bech32 prefix; expected cosmos, got mantle

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#28]
ReadListData() in listData.go file gives this error invalid Bech32 prefix; expected cosmos, got mantle
{"Test for some id", args{"mantle1x53dugvr4xvew442l9v2r5x7j8gfvged5xd3xr"}, NewListData(NewStringData("mantle1x53dugvr4xvew442l9v2r5x7j8gfvged5xd3xr")), assert.NoError},

https://github.com/AssetMantle/modules/blob/8963be3376df53e9816ecfd7ea61b667814da1d7/schema/data/base/listData.go

**Comment by deepanshutr** [comment]
for test cases, since the app configuration is not done, it will default to "cosmos". Can compare with same for test cases.

**Comment by deepanshutr** [comment]
adding configuration change for the test case
