### ISSUE TITLE
Initialize() in helpers panics with nil value

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#30]
Initialize() for auxiliary panics for nil value

https://github.com/AssetMantle/modules/blob/8963be3376df53e9816ecfd7ea61b667814da1d7/schema/helpers/base/auxiliary.go

**Comment by deepanshutr** [comment]
since this is a pre-application start initialization, panic is expected output of nil initialization

**Comment by deepanshutr** [comment]
panic is expected
