### ISSUE TITLE
validator() in parameters panics

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#32]
Panics for 
		{"-ve InvalidParameter", args{baseTypes.NewParameter(baseIDs.NewID(""), baseData.NewStringData(""), validator)}, errors.InvalidParameter},
		
https://github.com/AssetMantle/modules/blob/8963be3376df53e9816ecfd7ea61b667814da1d7/modules/assets/internal/parameters/dummy/validator.go

**Comment by deepanshutr** [comment]
couldn't find test case please elaborate

**Comment by deepanshutr** [comment]
found the issue, incorrect type assertion
