### ISSUE TITLE
NewIdentityID() panics for nil immutableProperties

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#33]
{"+ve nil", fields{classificationID, baseQualified.Immutables{PropertyList: nil}.GenerateHashID()}, append(classificationID.Bytes(), baseQualified.Immutables{PropertyList: nil}.GenerateHashID().Bytes()...)},

https://github.com/AssetMantle/modules/blob/8963be3376df53e9816ecfd7ea61b667814da1d7/modules/identities/internal/key/identityID.go

**Comment by deepanshutr** [comment]
adding nil check
