### ISSUE TITLE
DecData bytes generation

### ISSUE THREAD

**Issue by avkr003** [AssetMantle/modules#347]
https://github.com/AssetMantle/modules/blob/master/schema/data/base/decData.go#L43
should be `return []byte(decData.Get().String())` for fixed way of bytes generation otherwise `DecData{"0.3"}` and `NewDecData(sdk.MustNewDecFromStr("0.3"))` will have completely different Bytes and ID

**Comment by deepanshutr** [comment]
dec data's underlying data type string
