### ISSUE TITLE
validator() returning wrong value

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#35]
For data		{"-ve wrong parameter Type", args{baseTypes.NewParameter(baseIDs.NewID("newID"), baseData.NewStringData("newStringData"), validator)}, false},

it should return errors.InvalidParameter instead panics
https://github.com/AssetMantle/modules/blob/8963be3376df53e9816ecfd7ea61b667814da1d7/modules/identities/internal/parameters/dummy/validator.go

**Comment by deepanshutr** [comment]
please add the test case

**Comment by deepanshutr** [comment]
replicate issue, #32
