### ISSUE TITLE
parameter.Validate() is failing with error "openpgp: incorrect key"

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#36]
Test Data: 
	id, testData, _ := createTestInput(t)

		{"+ve", fields{id, testData, validator}, false},

Also For nil value it should not panic
https://github.com/AssetMantle/modules/blob/3e62f8cb40b10039df374e574e59a5f9518a135d/schema/parameters/base/parameter_test.go

**Comment by deepanshutr** [comment]
no test cases failing, @0xankit if you can elaborate/commit the failing test case
