### ISSUE TITLE
id_Compare is not properly implemented

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#37]
{"-ve", fields{"ID"}, args{NewID("ID2")}, 0},
for Above inputs it should result 1/-1 but it's passing that should not happen

https://github.com/AssetMantle/modules/blob/3e62f8cb40b10039df374e574e59a5f9518a135d/schema/ids/base/id.go

**Comment by deepanshutr** [comment]
there is a bug in the code:
strings.Compare(id.String(), id.String())
id has been compared with itself leading to false positive always.

**Comment by deepanshutr** [comment]
closing with https://github.com/AssetMantle/modules/commit/d51d5a2678727aa325b37d7155aafda414f54625
