### ISSUE TITLE
transactionKeeper have nil verifyAuxiliary

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#38]
transactionKeeper have nil verifyAuxiliary

if auxiliaryResponse := transactionKeeper.verifyAuxiliary.GetKeeper().Help(context, verify.NewAuxiliaryRequest(message.From, message.FromID)); !auxiliaryResponse.IsSuccessful()

**Comment by deepanshutr** [comment]
similar naming for verify maintainers and verify identities auxiliaries caused a confusion, renaming identities verify to authenticate and adding auxiliary.
