### ISSUE TITLE
Document fails to Mutate with nil

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#59]
for Test input:
`{"+ve with nil mutables", fields{ClassificationID: classificationID, Immutables: testImmutables, Mutables: mutables{}}, args{[]properties.Property{testMutateProperty}}, document{ClassificationID: classificationID, Immutables: testImmutables, Mutables: mutables{}}.Mutate(testMutateProperty)}, 
`
in [base/document.go](https://github.com/AssetMantle/modules/blob/59c9fb367277256a61af64e10ea15a39017683c8/schema/qualified/base/document.go#L41)

**Comment by deepanshutr** [comment]
fixed
