### ISSUE TITLE
Couldn't add in idList & propertyList

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#61]
https://github.com/AssetMantle/modules/blob/ed62da973c6f414265ccff0662a378e4d3feb484/schema/lists/base/idList_test.go#L30

https://github.com/AssetMantle/modules/blob/ed62da973c6f414265ccff0662a378e4d3feb484/schema/lists/base/propertyList_test.go#L76-L77

**Comment by deepanshutr** [comment]
one issue in getList found(recursive call) will fix. All else are issues in test cases
