### ISSUE TITLE
Search() in datalist & idList fails for empty struct

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#64]
https://github.com/AssetMantle/modules/blob/ed62da973c6f414265ccff0662a378e4d3feb484/schema/lists/base/dataList_test.go#L133

https://github.com/AssetMantle/modules/blob/ed62da973c6f414265ccff0662a378e4d3feb484/schema/lists/base/idList_test.go#L114

**Comment by deepanshutr** [comment]
resolved
