### ISSUE TITLE
couldn't mutate list in list.go & propertyList.go

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#65]
https://github.com/AssetMantle/modules/blob/ed62da973c6f414265ccff0662a378e4d3feb484/schema/lists/base/list_test.go#L90

https://github.com/AssetMantle/modules/blob/ed62da973c6f414265ccff0662a378e4d3feb484/schema/lists/base/propertyList_test.go#L159

**Comment by deepanshutr** [comment]
resolved
