### ISSUE TITLE
dataID panics for nil 

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#68]
https://github.com/AssetMantle/modules/blob/06910267a09ebe8fb67d551e2f5a52ecdfff7b20/schema/ids/base/dataID_test.go#L27

https://github.com/AssetMantle/modules/blob/06910267a09ebe8fb67d551e2f5a52ecdfff7b20/schema/ids/base/dataID_test.go#L78

https://github.com/AssetMantle/modules/blob/06910267a09ebe8fb67d551e2f5a52ecdfff7b20/schema/ids/base/dataID_test.go#L110

**Comment by deepanshutr** [comment]
adding nil check on constructor, these will be invalid test cases after that
