### ISSUE TITLE
panics for nil in NewMetaProperty()

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#73]
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L59
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L117
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L120
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L175-L176
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L203-L204
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L259-L260
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/metaProperty_test.go#L287-L288

**Comment by deepanshutr** [comment]
invalid test casese
