### ISSUE TITLE
panics for nil NewProperty() in property.go

### ISSUE THREAD

**Issue by 0xankit** [AssetMantle/modules#77]
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/property_test.go#L59
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/property_test.go#L141
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/property_test.go#L199
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/property_test.go#L255
https://github.com/AssetMantle/modules/blob/127e749d9f72167957645cea061ba269cc17757e/schema/properties/base/property_test.go#L283

**Comment by deepanshutr** [comment]
will add nil check on constructor, the test cases become invalid after
